global using System.Net;
global using System.Text;
global using System.Text.Json;
global using System.Text.RegularExpressions;
global using CliFx.Exceptions;
global using CliFx.Extensibility;
global using CliFx.Infrastructure;
global using MarkdownLinkCheckLogParserCli.CliCommands.ParseLog;
global using MarkdownLinkCheckLogParserCli.CliCommands.ParseLog.Exceptions;
global using MarkdownLinkCheckLogParserCli.CliCommands.ParseLog.Outputs.Exceptions;
global using MarkdownLinkCheckLogParserCli.Files;
global using MarkdownLinkCheckLogParserCli.GitHub.Exceptions;
global using MarkdownLinkCheckLogParserCli.Tests.Auxiliary;
global using NSubstitute;
global using Shouldly;
global using Xunit;
global using static MarkdownLinkCheckLogParserCli.Tests.Auxiliary.NewLines;
